sonor/urls.py
from django.urls import path
from . import views

app_name = 'sonor'

# Create your views here.
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),
]

sonor_photographie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from sonor_photographie import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sonor.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sonor/models.py
from django.db import models

# Create your models here.


class Tag(models.Model):
    class Meta:
        verbose_name = "Catégorie"

    name = models.CharField(
        verbose_name="nom", unique=True, null=False, blank=False, max_length=100
    )

    def __str__(self):
        return self.name


class Image(models.Model):
    name = models.CharField(
        verbose_name="nom", unique=True, null=False, blank=False, max_length=100
    )

    description = models.TextField(null=True, blank=True, max_length=300)

    image = models.ImageField(
        # images will be uploaded to /media/uploads/products
        upload_to="uploads/images/"
    )

    tags = models.ManyToManyField(
        to=Tag,
    )

    def __str__(self):
        return self.name

sonor/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpRequest
from django.shortcuts import render

# Create your views here.

def home(request: HttpRequest):

    return render(request, 'sonor/pages/home.html', {
        'current_page': 'home'
    })


def about(request: HttpRequest):

    return render(request, 'sonor/pages/about.html', {
        'current_page': 'about'
    })


def portfolio(request: HttpRequest):

    return render(request, 'sonor/pages/gallery.html', {
        'current_page': 'gallery'
    })


def contact(request: HttpRequest):

    return render(request, 'sonor/pages/contact.html', {
        'current_page': 'contact'
    })

sonor/templates/sonor/components/navbar.html
{% load static %}

<nav class="navbar">
    <a href="{% url 'sonor:home' %}" class="logo">
        <!-- <img src="{% static 'assets/logo.svg' %}" alt="Logo"> -->
        Sonor Photographie
    </a>
    <ul>
        <li class="{% if current_page == 'home' %}active{% endif %}"><a href="{% url 'sonor:home' %}">Accueil</a></li>
        <li class="{% if current_page == 'portfolio' %}active{% endif %}"><a href="{% url 'sonor:portfolio' %}">Gallerie</a></li>
        <li class="{% if current_page == 'about' %}active{% endif %}"><a href="{% url 'sonor:about' %}">A propos</a></li>
        <li class="{% if current_page == 'contact' %}active{% endif %}"><a href="{% url 'sonor:contact' %}">Contact</a></li>
    </ul>
</nav>

sonor/templates/sonor/layouts/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <title>Mon Portfolio</title>
</head>
<body>
    {% include 'sonor/components/navbar.html' %}
    
    {% block content %}
    {% endblock %}
</body>
</html>

sonor/templates/sonor/pages/about.html
{% extends 'sonor/layouts/main.html' %}
{% load static %}

{% block content %}
    <section class="about">
        <div class="about__info">
            <h1>Benoit Sthorez</h1>
            <h2>Sonor Photographie</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sint facilis eos harum aliquid libero possimus, quis accusantium, saepe hic ullam cumque. Maiores ratione eveniet facilis nihil quaerat tenetur modi assumenda.</p>
            <div class="btn-sci">
                <a class="btn-sci__cv" href="{% static 'documents/fake_cv.jpg' %}" target="_blank">Download CV</a>
                <div class="btn-sci__sci">
                    <a href=""><i class='bx bxl-github' ></i></a>
                    <a href=""><i class='bx bxl-linkedin' ></i></a>
                    <a href=""><i class='bx bxl-twitter' ></i></a>
                    <a href=""><i class='bx bxl-youtube' ></i></a>
                </div>
            </div>
        </div>

        <div class="about__img">
            <div class="about__img-box">
                <div class="about__img-item">
                    {# <img src="{% static 'images/photo.jpg' %}" alt="Photo"> #}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

sonor/templates/sonor/pages/contact.html
{% extends 'sonor/layouts/main.html' %}
{% load static %}



{% block content %}
    <section class="contact">
       Contact page
    </section>
{% endblock %}

sonor/templates/sonor/pages/gallery.html
{% extends 'sonor/layouts/main.html' %}
{% load static %}



{% block content %}
    <section class="gallery">
        Gallery page
    </section>
{% endblock %}

sonor/templates/sonor/pages/home.html
{% extends 'sonor/layouts/main.html' %}
{% load static %}



{% block content %}
    <section class="home">
        <h1>Sonor Photographie</h1>
        <p>{% lorem 9 w random %}</p>
    </section>
{% endblock %}